### ISSUE TITLE
Neo4j 4.0.1 fails to import ontologies

### ISSUE THREAD

**Issue by StrangeTcy** [neo4j-labs/neosemantics#151]
On Ubuntu 18.04 with neo4j 4.0.1 and neosemantics 3.5.0.4 (latest release at the time of this writing) I try to reproduce the results from[ quickgraph #9](https://jbarrasa.com/2019/11/25/quickgraph9-the-fashion-knowledge-graph-inferencing-with-ontologies-in-neo4j/), but running the 

> CALL semantics.importOntology(
>     "http://www.nsmntx.org/2019/10/clothingMaterials",
>     "Turtle", { keepLangTag: true, handleMultival: 'ARRAY'})

query results in an error:

> Failed to invoke procedure `semantics.importOntology`: Caused by: java.lang.NoSuchMethodError: 'org.neo4j.graphdb.schema.Schema org.neo4j.graphdb.GraphDatabaseService.schema()'

At the same time, a simple `call semantics.importOntology()` gets an expected error about no arguments being provided.

My guess is that neosemantics 3.5 can't find some method in neo4j 4.0 due to some renaming, but probably that's not the cause of this.

**Comment by jbarrasa** [comment]
Yes, the 3.5.x releases of neosemantics were not compatible with Neo4j 4.0. Hopefully you'll be able to make it work with the 4.0.x release.
The syntax will change a bit, as described in the [migration guide](https://neo4j.com/docs/labs/nsmntx/current/appendix_migration/), but it should be pretty straightforward:
`CALL n10s.graphconfig.init({ keepLangTag: true, handleMultival: 'ARRAY'});`
`CALL n10s.onto.import.fetch("http://www.nsmntx.org/2019/10/clothingMaterials",
"Turtle"); `

Please comment if you find any issue.

Cheers,

JB.

**Comment by jexp** [comment]
Closing as stale. Reported against an old version of Neo4j (4.x or earlier) that is no longer supported. If still reproducible with current 5.x/2025.x + latest neosemantics, please open a new issue with full version details and a reproducible example.
